#!/bin/bash
# Update the package repository
sudo yum update -y
# Install Docker
sudo amazon-linux-extras install docker -y
# Start Docker service
sudo service docker start
# Enable Docker service to start on boot
sudo systemctl enable docker
# Add the ec2-user to the docker group
sudo usermod -a -G docker ec2-user
